CXX = g++

CXX_ARGS = -c -Wall -Wextra -std=c++17 -Istdlib

BUILD_DIR = output
SRC_DIR = board_source

CXX_FILES = $(wildcard $(SRC_DIR)/*.cpp)

OBJ_FILES = $(CXX_FILES:$(SRC_DIR)/%.cpp=output/%_src.o)

TARGET = source.so

.PHONY: clean

all: $(TARGET)

$(BUILD_DIR)/%_src.o: $(SRC_DIR)/%.cpp
	@if [[ ! -d "output" ]]; then mkdir output; fi
	$(CXX) $(CXX_ARGS) $< -o $@

$(TARGET): $(OBJ_FILES)
	$(CXX) -o $(TARGET) $(OBJ_FILES)

clean:
	rm -r output $(TARGET)
